name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      DB_NAME: golang
      DB_USER: root
      DB_PASSWORD: root
      DB_DSN: $DB_USER:$DB_PASSWORD@/$DB_NAME

    steps:
    - uses: actions/checkout@v3

    - name: Set up Mysql
      run : |
          sudo /etc/init.d/mysql start
          mysql -v
          mysql -h 127.0.0.1 -e 'CREATE DATABASE ${{ env.DB_NAME }};' -u ${{ env.DB_USER }} -p ${{ env.DB_PASSWORD }} 

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test hw6
      run:  go test -v ./hw6_db_explorer
